// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/get-todays-menu.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/menuSource.ts
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL is not configured");
  return url;
}
function publishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("No Supabase publishable key is configured");
}
async function fetchWeeklyMenu() {
  const key = publishableKey();
  const res = await fetch(`${supabaseProjectUrl()}/functions/v1/get-daily-menu`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      apikey: key,
      Authorization: `Bearer ${key}`
    },
    body: "{}"
  });
  if (!res.ok) throw new Error(`Menu service returned ${res.status}`);
  const json = await res.json();
  if (!json.success || !json.data) return null;
  return json.data;
}
var WEEKDAY_KEYS = ["sonntag", "montag", "dienstag", "mittwoch", "donnerstag", "freitag", "samstag"];
function pickToday(menu) {
  const viennaNow = new Date(
    (/* @__PURE__ */ new Date()).toLocaleString("en-US", { timeZone: "Europe/Vienna" })
  );
  const key = WEEKDAY_KEYS[viennaNow.getDay()];
  return menu.days.find((d) => d.day.de.toLowerCase().includes(key)) ?? null;
}
function formatDay(day, lang) {
  const lines = [
    `${day.day[lang]}`,
    `  Soup: ${day.soup[lang] || "-"}`,
    `  Green: ${day.green[lang] || "-"}${day.greenNote?.[lang] ? ` (${day.greenNote[lang]})` : ""}`,
    `  Blue: ${day.blue[lang] || "-"}${day.blueNote?.[lang] ? ` (${day.blueNote[lang]})` : ""}`
  ];
  return lines.join("\n");
}

// src/lib/mcp/tools/get-todays-menu.ts
var get_todays_menu_default = defineTool({
  name: "get_todays_menu",
  title: "Today's menu",
  description: "Get today's daily dishes (soup, green and blue dish) at My Secret Garden in Vienna. Sunday is closed.",
  inputSchema: {
    language: z.enum(["de", "en"]).default("de").describe("Language of the dish names: German (de) or English (en).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ language }) => {
    const lang = language ?? "de";
    try {
      const menu = await fetchWeeklyMenu();
      const today = menu ? pickToday(menu) : null;
      if (!today) {
        return {
          content: [
            {
              type: "text",
              text: "No daily menu for today. We are closed on Sundays and public holidays; the new weekly menu goes online on Monday morning."
            }
          ]
        };
      }
      return {
        content: [{ type: "text", text: formatDay(today, lang) }],
        structuredContent: { day: today }
      };
    } catch (error) {
      return {
        content: [{ type: "text", text: `Menu not available right now: ${error.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/get-weekly-menu.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_weekly_menu_default = defineTool2({
  name: "get_weekly_menu",
  title: "Weekly menu",
  description: "Get the current weekly changing menu (soup, green and blue dish per day) of My Secret Garden in Vienna.",
  inputSchema: {
    language: z2.enum(["de", "en"]).default("de").describe("Language of the dish names: German (de) or English (en).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ language }) => {
    const lang = language ?? "de";
    try {
      const menu = await fetchWeeklyMenu();
      if (!menu) {
        return {
          content: [
            { type: "text", text: "The weekly menu is not published right now. Come visit us or call +43 1 586 28 39." }
          ]
        };
      }
      const text = [`Weekly menu (${menu.period})`, ...menu.days.map((d) => formatDay(d, lang))].join("\n\n");
      return { content: [{ type: "text", text }], structuredContent: { period: menu.period, days: menu.days } };
    } catch (error) {
      return {
        content: [{ type: "text", text: `Menu not available right now: ${error.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/get-classics-menu.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";

// src/data/klassikerData.ts
var klassikerMenu = {
  title: { de: "Unsere Klassiker", en: "Our Classics" },
  subtitle: { de: "Dal, Salate, Kuchen und Getr\xE4nke, die fast jeden Tag da sind.", en: "Dal, salads, cakes and drinks that are here almost every day." },
  categories: [
    {
      id: "warm",
      name: { de: "Warme Speisen", en: "Warm Dishes" },
      items: [
        {
          id: "indisches-dal",
          name: { de: "Indisches Dal", en: "Indian Dal" },
          description: {
            de: "Cremige rote Linsen, Zwiebeln und Tomaten mit indischen Gew\xFCrzen; dazu Basmatireis",
            en: "Creamy red lentils, onions and tomatoes with Indian spices; served with basmati rice"
          },
          price: "9,90",
          isVegan: true,
          isGlutenFree: true,
          descriptionShort: "cremig, Linsen, w\xFCrzig",
          ingredientsMain: ["Rote Linsen", "Tomaten", "Zwiebeln", "indische Gew\xFCrze", "Basmatireis"],
          gfDisclaimer: true
        }
      ]
    },
    {
      id: "salate",
      name: { de: "Salate", en: "Salads" },
      items: [
        {
          id: "bunter-salat",
          name: { de: "Secret Garden Salat", en: "Secret Garden Salad" },
          description: {
            de: "Frischer Blattsalat mit saisonalem Gem\xFCse und hausgemachtem Dressing",
            en: "Fresh leaf salad with seasonal vegetables and homemade dressing"
          },
          price: "6,5 / 10,9",
          isVegan: true,
          isGlutenFree: true,
          descriptionShort: "frisch, saisonales Gem\xFCse",
          ingredientsMain: ["Blattsalat", "saisonales Gem\xFCse", "hausgemachtes Dressing"],
          gfDisclaimer: true
        },
        {
          id: "secret-garden-avocado",
          name: { de: "Secret Garden Salat mit Avocado", en: "Secret Garden Salad with Avocado" },
          description: {
            de: "Bunter Salat mit frischer Avocado und hausgemachtem Dressing",
            en: "Colorful salad with fresh avocado and homemade dressing"
          },
          price: "17,5",
          isVegan: true,
          isGlutenFree: true,
          descriptionShort: "frisch, Avocado, saisonal",
          ingredientsMain: ["Blattsalat", "Avocado", "saisonales Gem\xFCse", "hausgemachtes Dressing"],
          gfDisclaimer: true
        },
        {
          id: "secret-garden-ziegenkase",
          name: { de: "Secret Garden Salat mit Ziegenk\xE4se", en: "Secret Garden Salad with Goat Cheese" },
          description: {
            de: "Bunter Salat mit warmem Ziegenk\xE4se und hausgemachtem Dressing",
            en: "Colorful salad with warm goat cheese and homemade dressing"
          },
          price: "17,5",
          isGlutenFree: true,
          descriptionShort: "frisch, warm, cremig",
          ingredientsMain: ["Blattsalat", "Ziegenk\xE4se", "saisonales Gem\xFCse", "hausgemachtes Dressing"],
          allergens: ["G"],
          gfDisclaimer: true
        },
        {
          id: "secret-garden-tofu",
          name: { de: "Secret Garden Salat mit Tofu", en: "Secret Garden Salad with Tofu" },
          description: {
            de: "Bunter Salat mit mariniertem Bio-Tofu und hausgemachtem Dressing",
            en: "Colorful salad with marinated organic tofu and homemade dressing"
          },
          price: "17,5",
          isVegan: true,
          isGlutenFree: true,
          isBio: true,
          descriptionShort: "frisch, Bio-Tofu, saisonal",
          ingredientsMain: ["Blattsalat", "Bio-Tofu", "saisonales Gem\xFCse", "hausgemachtes Dressing"],
          allergens: ["F"],
          gfDisclaimer: true,
          ingredientProducers: { Tofu: { certification: "bio" } }
        }
      ]
    },
    {
      id: "suesses",
      name: { de: "S\xFC\xDFes", en: "Sweets" },
      items: [
        {
          id: "vegan-cheesecake",
          name: { de: "Veganer Cheesecake", en: "Vegan Cheesecake" },
          description: {
            de: "Cremiger veganer K\xE4sekuchen",
            en: "Creamy vegan cheesecake"
          },
          price: "4,90",
          isVegan: true,
          isGlutenFree: true,
          descriptionShort: "cremig, vegan, s\xFC\xDF",
          ingredientsMain: ["vegane Creme", "Kuchenboden"],
          allergens: ["H"],
          gfDisclaimer: true
        },
        {
          id: "karamellschnitte",
          name: { de: "Karamellschnitte", en: "Caramel Slice" },
          description: {
            de: "Hausgemachte Karamellschnitte",
            en: "Homemade caramel slice"
          },
          price: "4,90",
          isVegan: true,
          isGlutenFree: true,
          descriptionShort: "s\xFC\xDF, Karamell, hausgemacht",
          ingredientsMain: ["Karamell", "Kuchenboden"],
          gfDisclaimer: true
        },
        {
          id: "walnuss-brownie",
          name: { de: "Walnuss-Brownie", en: "Walnut Brownie" },
          description: {
            de: "Saftiger Schokoladen-Brownie mit Waln\xFCssen",
            en: "Moist chocolate brownie with walnuts"
          },
          price: "4,7",
          isVegan: true,
          isGlutenFree: true,
          descriptionShort: "schokoladig, Walnuss",
          ingredientsMain: ["Schokolade", "Waln\xFCsse"],
          allergens: ["H"],
          gfDisclaimer: true
        },
        {
          id: "schoko-mousse-torte",
          name: { de: "Schoko Mousse Torte", en: "Chocolate Mousse Cake" },
          description: {
            de: "Luftige Schokoladenmousse-Torte",
            en: "Light chocolate mousse cake"
          },
          price: "4,7",
          descriptionShort: "cremig, Schokolade",
          ingredientsMain: ["Schokolade", "Mousse", "Kuchenboden"],
          allergens: ["A", "C", "G"]
        },
        {
          id: "karotten-gewuerztorte",
          name: { de: "Karotten-Gew\xFCrztorte", en: "Carrot Spice Cake" },
          description: {
            de: "W\xFCrzige Karottentorte mit Frischk\xE4se-Topping",
            en: "Spiced carrot cake with cream cheese topping"
          },
          price: "4,5",
          isVegan: true,
          descriptionShort: "w\xFCrzig, Karotte, cremig",
          ingredientsMain: ["Karotten", "Gew\xFCrze", "veganes Topping"],
          allergens: ["A", "H"]
        }
      ]
    },
    {
      id: "getraenke",
      name: { de: "Hausgemachte Getr\xE4nke", en: "Homemade Drinks" },
      items: [
        {
          id: "ingwer-limo",
          name: { de: "Ingwer-Limo", en: "Ginger Lemonade" },
          description: {
            de: "Erfrischende hausgemachte Ingwerlimonade",
            en: "Refreshing homemade ginger lemonade"
          },
          price: "3,00 / 4,70",
          isVegan: true,
          descriptionShort: "frisch, Ingwer, spritzig",
          ingredientsMain: ["Ingwer", "Zitrone"]
        },
        {
          id: "eistee",
          name: { de: "Hausgemachter Eistee", en: "Homemade Iced Tea" },
          description: {
            de: "Frisch gebr\xFChter Eistee mit nat\xFCrlichen Zutaten",
            en: "Freshly brewed iced tea with natural ingredients"
          },
          price: "4,2",
          isVegan: true,
          isUnavailable: true,
          descriptionShort: "frisch, Tee, hausgemacht",
          ingredientsMain: ["Tee", "nat\xFCrliche Zutaten"]
        },
        {
          id: "mango-lassi",
          name: { de: "Mango-Lassi", en: "Mango Lassi" },
          description: {
            de: "Cremiger Joghurt-Drink mit frischer Mango",
            en: "Creamy yogurt drink with fresh mango"
          },
          price: "4,9",
          descriptionShort: "cremig, Mango",
          ingredientsMain: ["Joghurt", "Mango"],
          allergens: ["G"]
        }
      ]
    },
    {
      id: "drinks",
      name: { de: "Getr\xE4nke", en: "Drinks" },
      subcategories: [
        {
          id: "hot-drinks",
          name: { de: "Hei\xDFgetr\xE4nke", en: "Hot Drinks" },
          items: [
            { id: "indian-chai-latte", name: { de: "Indian Chai Latte", en: "Indian Chai Latte" }, price: "4,9" },
            { id: "matcha-latte", name: { de: "Matcha Latte", en: "Matcha Latte" }, price: "5,4" },
            { id: "glueh-kombucha", name: { de: '"Gl\xFCh" Kombucha', en: '"Gl\xFCh" Kombucha (hot)' }, price: "4,9" },
            { id: "kurkuma-latte", name: { de: "Kurkuma Latte", en: "Kurkuma Latte" }, price: "4,9" },
            { id: "espresso", name: { de: "Espresso", en: "Espresso" }, sizeNote: "1 Shot / 2 Shots", price: "2,9 / 3,9" },
            { id: "verlaengerter", name: { de: "Verl\xE4ngerter / Americano", en: "Verl\xE4ngerter / Americano" }, sizeNote: "kurz / lang \xB7 short / long", price: "3,5 / 4,5" },
            { id: "cappuccino", name: { de: "Cappuccino / Melange", en: "Cappuccino / Melange" }, sizeNote: "1 Shot / 2 Shots", price: "4,3 / 5,7" },
            { id: "flat-white", name: { de: "Flat White", en: "Flat White" }, price: "5,2" },
            { id: "latte-macchiato", name: { de: "Latte Macchiato", en: "Latte Macchiato" }, price: "5,2" },
            { id: "chaga-kaffee", name: { de: "Chaga Kaffee", en: "Chaga Kaffee" }, price: "5,5" },
            { id: "blue-magic-tea", name: { de: "Blue Magic Tea", en: "Blue Magic Tea" }, price: "3,9" }
          ]
        },
        {
          id: "cold-drinks",
          name: { de: "Kaltgetr\xE4nke", en: "Cold Drinks" },
          items: [
            { id: "strawberry-spritz", name: { de: "Strawberry Spritz", en: "Strawberry Spritz" }, sizeNote: "Erdbeer-Tonic & Soda \xB7 strawberry tonic & soda", price: "6,5", isNew: true },
            { id: "iced-strawberry-matcha", name: { de: "Iced Strawberry Matcha Latte", en: "Iced Strawberry Matcha Latte" }, sizeNote: "0,3 l", price: "6,5", isNew: true },
            { id: "iced-espresso-tonic", name: { de: "Iced Espresso Tonic", en: "Iced Espresso Tonic" }, sizeNote: "0,18 l", price: "5,5", isNew: true },
            { id: "cold-brew", name: { de: "Cold Brew", en: "Cold Brew" }, sizeNote: "0,18 l", price: "4,9", isNew: true },
            { id: "ginger-limo", name: { de: "Ingwer-Limo", en: "Ginger Limo" }, sizeNote: "0,2 l / 0,5 l", price: "3,0 / 4,7" }
          ]
        },
        {
          id: "juices",
          name: { de: "S\xE4fte vom \xF6sterreichischen Bauernhof", en: "Juices from the Austrian Farm" },
          sizeNote: "0,2 l / 0,5 l",
          items: [
            { id: "apple-juice", name: { de: "Apfelsaft gespritzt", en: "Apple Juice with Water or Soda" }, price: "2,9 / 4,5" },
            { id: "peach-juice", name: { de: "Pfirsichsaft gespritzt", en: "Peach Juice with Water or Soda" }, price: "3,0 / 4,7" },
            { id: "elderflower", name: { de: "Holundersirup gespritzt", en: "Elderflower Syrup with Water or Soda" }, price: "2,7 / 4,2" }
          ]
        },
        {
          id: "organic-sodas",
          name: { de: "Bio-Limonaden", en: "Organic Sodas" },
          sizeNote: "0,33 l",
          items: [
            { id: "cola", name: { de: "Cola", en: "Cola" }, price: "3,9" },
            { id: "pomegranate", name: { de: "Granatapfel", en: "Pomegranate" }, price: "3,9" },
            { id: "orange-acerola", name: { de: "Orange-Acerola", en: "Orange-Acerola" }, price: "3,9" },
            { id: "green-tea-soda", name: { de: "Gr\xFCner Tee", en: "Green Tea" }, price: "3,9" }
          ]
        },
        {
          id: "more-cold-drinks",
          name: { de: "Weitere Kaltgetr\xE4nke", en: "More Cold Drinks" },
          items: [
            { id: "goesser-beer", name: { de: "G\xF6sser Alkoholfrei", en: "G\xF6sser Non-Alcoholic Beer" }, sizeNote: "0,5 l", price: "4,5" },
            { id: "coconut-water", name: { de: "Bio Kokoswasser", en: "Organic Coconut Water" }, sizeNote: "0,2 l / 0,5 l", price: "3,7 / 5,7" },
            { id: "mineral-water", name: { de: "Mineralwasser still oder prickelnd", en: "Mineral Water Still or Sparkling" }, sizeNote: "0,33 l", price: "2,5" },
            { id: "lemon-soda", name: { de: "Zitronenlimonade", en: "Lemon Soda" }, sizeNote: "0,2 l / 0,5 l", price: "2,7 / 3,9" },
            { id: "glass-water", name: { de: "Wasser aus Glasflaschen", en: "Water from our Glass-Bottles" }, price: "0,7" }
          ]
        }
      ]
    }
  ]
};

// src/lib/mcp/tools/get-classics-menu.ts
function formatItem(item, lang) {
  const flags = [
    item.isVegan ? "vegan" : null,
    item.isGlutenFree ? "gluten-free" : null,
    item.isBio ? "bio" : null
  ].filter(Boolean);
  const desc = item.description?.[lang];
  return `- ${item.name[lang]} \u2014 ${item.price} \u20AC${flags.length ? ` [${flags.join(", ")}]` : ""}${desc ? `
    ${desc}` : ""}`;
}
var get_classics_menu_default = defineTool3({
  name: "get_classics_menu",
  title: "Classics, cakes and drinks",
  description: "Get the permanent menu of My Secret Garden: warm dishes, salads, cakes and drinks that are available almost every day.",
  inputSchema: {
    language: z3.enum(["de", "en"]).default("de").describe("Language of the menu: German (de) or English (en)."),
    category: z3.string().optional().describe("Optional category filter, e.g. 'salate', 'kuchen', 'getraenke', 'warm'. Omit for the full menu.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ language, category }) => {
    const lang = language ?? "de";
    const needle = category?.trim().toLowerCase();
    const categories = klassikerMenu.categories.filter((cat) => {
      if (!needle) return true;
      return cat.id.toLowerCase().includes(needle) || cat.name.de.toLowerCase().includes(needle) || cat.name.en.toLowerCase().includes(needle);
    });
    if (categories.length === 0) {
      return {
        content: [
          {
            type: "text",
            text: `No category matches "${category}". Available: ${klassikerMenu.categories.map((c) => c.id).join(", ")}.`
          }
        ],
        isError: true
      };
    }
    const blocks = categories.map((cat) => {
      const direct = (cat.items ?? []).map((i) => formatItem(i, lang));
      const subs = (cat.subcategories ?? []).map(
        (sub) => [`  ${sub.name[lang]}${sub.sizeNote ? ` (${sub.sizeNote})` : ""}`, ...sub.items.map((i) => `  ${formatItem(i, lang)}`)].join("\n")
      );
      return [`${cat.name[lang]}`, ...direct, ...subs].join("\n");
    });
    return {
      content: [{ type: "text", text: [klassikerMenu.title[lang], "", ...blocks].join("\n\n") }],
      structuredContent: { categories }
    };
  }
});

// src/lib/mcp/tools/get-visit-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var INFO = {
  name: "My Secret Garden",
  address: "Mariahilferstra\xDFe 45, Im Raimundhof, 1060 Wien, Austria",
  phone: "+43 1 586 28 39",
  hours: "Monday to Saturday 11:00-19:00. Sunday and public holidays closed.",
  website: "https://secretgardenrestaurant.at",
  de: {
    finding: "Wir liegen im Innenhof des Raimundhofs. Vom Gehsteig durch den Torbogen, dann links. Der Garten \xF6ffnet sich hinter der Einfahrt.",
    service: "Du bestellst direkt am Tresen, suchst dir deinen Platz und wir bringen dir das Essen.",
    transport: "U-Bahn: U3 Neubaugasse, 2 Gehminuten. Parken: Wipark Windm\xFChlgasse 22-24, erste Stunde geschenkt.",
    kitchen: "Vegetarische und vegane K\xFCche, viele glutenfreie Gerichte, bio und saisonal."
  },
  en: {
    finding: "We are in the courtyard of Raimundhof. From the street, walk through the archway and turn left; the garden opens up behind the entrance.",
    service: "Order at the counter, pick your seat, and we bring the food to you.",
    transport: "Metro U3 Neubaugasse, 2 minutes on foot. Parking: Wipark Windm\xFChlgasse 22-24, first hour on us.",
    kitchen: "Vegetarian and vegan kitchen, many gluten-free dishes, organic and seasonal."
  }
};
function openNow() {
  const vienna = new Date((/* @__PURE__ */ new Date()).toLocaleString("en-US", { timeZone: "Europe/Vienna" }));
  const day = vienna.getDay();
  const minutes = vienna.getHours() * 60 + vienna.getMinutes();
  const open = day !== 0 && minutes >= 11 * 60 && minutes < 19 * 60;
  return {
    open,
    note: open ? "Open right now (Vienna time)." : "Closed right now (Vienna time)."
  };
}
var get_visit_info_default = defineTool4({
  name: "get_visit_info",
  title: "Visit info",
  description: "Get address, opening hours, current open/closed status, phone number and directions for My Secret Garden, a vegetarian and vegan restaurant in Vienna.",
  inputSchema: {
    language: z4.enum(["de", "en"]).default("de").describe("Language of the notes: German (de) or English (en).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ language }) => {
    const lang = language ?? "de";
    const status = openNow();
    const localized = INFO[lang];
    const text = [
      INFO.name,
      INFO.address,
      `Phone: ${INFO.phone}`,
      `Hours: ${INFO.hours}`,
      status.note,
      localized.kitchen,
      localized.finding,
      localized.service,
      localized.transport,
      INFO.website
    ].join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: {
        name: INFO.name,
        address: INFO.address,
        phone: INFO.phone,
        hours: INFO.hours,
        openNow: status.open,
        website: INFO.website
      }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cqgcriywwsdvwqefbnhx";
var mcp_default = defineMcp({
  name: "secret-garden-vegan",
  title: "Secret Garden Vegan",
  version: "0.1.0",
  instructions: "Public tools for My Secret Garden, a vegetarian and vegan cafe restaurant in Vienna (Mariahilferstra\xDFe 45, Im Raimundhof). Use get_todays_menu for today's dishes, get_weekly_menu for the whole week, get_classics_menu for the permanent dishes, cakes and drinks, and get_visit_info for address, opening hours and directions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_todays_menu_default, get_weekly_menu_default, get_classics_menu_default, get_visit_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
